### ISSUE TITLE
Clean self-node on disconnect.

### ISSUE THREAD

**Issue by jasongoodwin** [typesafehub/constructr-zookeeper#21]
I don't believe Self-Nodes should live after disconnect from zookeeper. The library recreates nodes while the curator inter process semaphone mutex uses an ephemeral mechanism. 
I believe that the library should be modified so that the nodes are written to zookeeper as ephemeral nodes to tie them to the connection, or at least clean the nodes on shutdown? TTL wasn't a mechanism in zookeeper until recently and isn't needed for service discovery. Basically, if you rip down a cluster, you shouldn't have to wait for the expiry before spinning it back up.

I have a quick example of clean up here (time constraints atm) but I believe ephemeral self-publishing should be considered instead.
https://github.com/jasongoodwin/constructr-zookeeper

Let me know if I'm misunderstanding anything.

**Comment by markusjura** [comment]
@jasongoodwin Your comment is reasonable. Why have you closed the issue?

**Comment by jasongoodwin** [comment]
I spent some time observing the behavior and the TTL mechanism appears to work well enough in my local environment. There are some other issues I'm observing while deploying into DC/OS - I'm going to comb over the library when I get some time and will provide back PRs for these items shortly.

Thanks!
